### ISSUE TITLE
'Error: Cannot find module "."' when using webpack

### ISSUE THREAD

**Issue by MichaelMure** [sindresorhus/lazy-req#6]
Hi,

I'm using a npm package that has lazi-req as a dependency. I'm using webpack to bundle my application.

The line:
```javascript
const lazyReq = require('lazy-req')(require);`
```
is bundled by webpack as the following:
```javascript
var lazyReq = __webpack_require__("./node_modules/bin-wrapper/node_modules/lazy-req/index.js")(!(function webpackMissingModule() {
    var e = new Error("Cannot find module \".\"");
    e.code = 'MODULE_NOT_FOUND';
    throw e;
}()));
```
As I understand, webpack replace the `require` function that should be passed to lazy-req and try to import a module named `.`, as no name is given. Obviously, it fails.

Is there a way to avoid that ?

Thank you

**Comment by sindresorhus** [comment]
Ask or open an issue on Webpack.

**Comment by r4j4h** [comment]
To be helpful for people in the future, see https://github.com/webpack/webpack/issues/4596
